general:
  auth:
    default: default
project:
  name: solodev-kubernetes
  owner: help@solodev.com
  shorten_stack_name: true
  regions:
  - us-east-1
  template: nodegroup.yaml
  parameters:
    Subnet1ID: subnet-79297656
    EKSClusterName: tmp-kube-060845
  lambda_source_path: functions/source
  lambda_zip_path: functions/packages
  build_submodules: true
tests:
  defaults:
    parameters:
      AvailabilityZones: $[taskcat_genaz_3]
