AWSTemplateFormatVersion: "2010-09-09"
Description: Deploys Solodev Webstack for Kubernetes

Parameters:
  ClusterName:
    Type: String
    Default: ""
  WebStackArn:
    Type: String
    Default: ""
  AdminEmail:
    Type: String
    Default: ""
    Description: "What is your email address?"
  ProvisionNginxIngress:
    Type: String
    AllowedValues: [ "Enabled", "Disabled" ]
    Default: "Enabled"
    Description: "Choose Enabled to enable Inginx Proxy"
  ProvisionExternalDNS:
    Type: String
    AllowedValues: [ "Enabled", "Disabled" ]
    Default: "Enabled"
    Description: "Choose Enabled to enable External DNS with Route 53"
  ProvisionDashboard:
    Type: String
    AllowedValues: [ "Enabled", "Disabled" ]
    Default: "Enabled"
    Description: "Choose Enabled to enable Dashboard"
  ProvisionAccessToken:
    Type: String
    AllowedValues: [ "Enabled", "Disabled" ]
    Default: "Enabled"
    Description: "Choose Enabled to enable Token"

Conditions:
  EnableNginxIngress: !Equals [!Ref 'ProvisionNginxIngress', 'Enabled']
  EnableExternalDNS: !Equals [!Ref 'ProvisionExternalDNS', 'Enabled']
  EnableDashboard: !Equals [!Ref 'ProvisionDashboard', 'Enabled']
  EnableAccessToken: !Equals [!Ref 'ProvisionAccessToken', 'Enabled']

Resources:
  
  #============================================================================#
  # Web Stack
  #============================================================================#
  
  DashboardStack:
    Condition: EnableDashboard
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://s3.amazonaws.com/solodev-kubernetes/cloudformation/webstack/webstack-dashboard.template.yaml
      Parameters:
        ClusterName: !Ref ClusterName
        WebStackArn: !Ref WebStackArn
  NginxIngressStack:
    Condition: EnableNginxIngress
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://s3.amazonaws.com/solodev-kubernetes/cloudformation/webstack/webstack-nginx-ingress.template.yaml
      Parameters:
        ClusterName: !Ref ClusterName
  ExternalDNSStack:
    Condition: EnableExternalDNS
    Type: AWS::CloudFormation::Stack
    Properties: 
      TemplateURL: https://s3.amazonaws.com/solodev-kubernetes/cloudformation/webstack/webstack-external-dns.template.yaml
      Parameters:
        ClusterName: !Ref ClusterName
  LetsEncryptStack:
    Condition: EnableNginxIngress
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://s3.amazonaws.com/solodev-kubernetes/cloudformation/webstack/webstack-lets-encrypt.template.yaml
      Parameters:
        ClusterName: !Ref ClusterName
        AdminEmail: !Ref AdminEmail
  # AccessTokenStack:
  #   DependsOn: DashboardStack
  #   Condition: EnableAccessToken
  #   Type: AWS::CloudFormation::Stack
  #   Properties:
  #     TemplateURL: https://s3.amazonaws.com/solodev-kubernetes/cloudformation/webstack/webstack-token.template.yaml
  #     Parameters:
  #       ClusterName: !Ref ClusterName
  #       WebStackArn: !Ref WebStackArn