AWSTemplateFormatVersion: "2010-09-09"
Description: Deploys a Solodev Optimized EKS cluster into an existing VPC
Parameters:
  VPCID:
    Type: "AWS::EC2::VPC::Id"
    Description: The ID of your existing VPC (e.g., vpc-0343606e)
  PublicSubnet1ID:
    Type: String
    Description: The ID of the public subnet in Availability Zone 1 in your existing VPC (e.g., subnet-a0246dcd)
    Default: ""
  PublicSubnet2ID:
    Type: String
    Description: The ID of the public subnet in Availability Zone 2 in your existing VPC (e.g., subnet-b1236eea)
    Default: ""
  PublicSubnet3ID:
    Type: String
    Description: The ID of the public subnet in Availability Zone 3 in your existing VPC (e.g., subnet-c3456aba)
    Default: ""
  PrivateSubnet1ID:
    Type: "AWS::EC2::Subnet::Id"
    Description: The ID of the private subnet in Availability Zone 1 in your existing VPC (e.g., subnet-fe9a8b32)
  PrivateSubnet2ID:
    Type: String
    Description: The ID of the private subnet in Availability Zone 2 in your existing VPC (e.g., subnet-be8b01ea)
    Default: ""
  PrivateSubnet3ID:
    Type: String
    Description: The ID of the private subnet in Availability Zone 3 in your existing VPC (e.g., subnet-abd39039)
    Default: ""
  AdminEmail:
    Type: String
    Default: ""
    Description: "What is your email address?"
  ControlPlaneSecurityGroup:
    Type: String
    Default: ""
  KubernetesAdminRoleArn:
    Type: String
    Default: ""
  SubnetIds:
    Type: String
    Default: ""
  ClusterName:
    Type: String
    Default: ""

Resources:
  
  #============================================================================#
  # Web Stack
  #============================================================================#

  WebStack:
    Type: "AWS::CloudFormation::Stack"
    DependsOn: ControlPlane
    Properties:
      TemplateURL: https://s3.amazonaws.com/solodev-kubernetes/cloudformation/webstack.yaml
      Parameters:
        VPCID: !Ref VPCID
        ControlPlaneSecurityGroup: !Ref ControlPlaneSecurityGroup
        KubernetesAdminRoleArn: !Ref KubernetesAdminRoleArn
        SubnetIds: !Ref SubnetIds
        ClusterName: !Ref ClusterName
        AdminEmail: !Ref AdminEmail