AWSTemplateFormatVersion: "2010-09-09"
Description: Deploys Solodev Webstack for Kubernetes

Parameters:
  ClusterName:
    Type: String
    Default: ""
  WebStackArn:
    Type: String
    Default: ""
  AdminEmail:
    Type: String
    Default: ""
    Description: "What is your email address?"
  ProvisionNginxIngress:
    Type: String
    AllowedValues: [ "Enabled", "Disabled" ]
    Default: "Enabled"
    Description: "Choose Enabled to enable Inginx Proxy"
  ProvisionExternalDNS:
    Type: String
    AllowedValues: [ "Enabled", "Disabled" ]
    Default: "Enabled"
    Description: "Choose Enabled to enable External DNS with Route 53"
  ProvisionDashboard:
    Type: String
    AllowedValues: [ "Enabled", "Disabled" ]
    Default: "Enabled"
    Description: "Choose Enabled to enable Dashboard"
  ProvisionNetwork:
    Type: String
    AllowedValues: [ "Enabled", "Disabled" ]
    Default: "Enabled"
    Description: "Choose Enabled to enable Token"
  CloudClientId:
    Type: String
    Description: AWS Cognito App Id
    Default: ""
  CloudClientSecret:
    Type: String
    Description: AWS Cognito App Secret
    Default: ""
  CloudRedirectURI:
    Type: String
    Default: ""
  CloudAuthorizeURL:
    Type: String
    Default: ""
  CloudAccessToken:
    Type: String
    Default: ""
  CloudKeySet:
    Type: String
    Default: ""
  OIDCUrl:
    Type: String
    Description: "OIDC Url format: https://oidc.eks:<region>.amazonaws.com/id/<providerid>"

Conditions:
  EnableNginxIngress: !Equals [!Ref 'ProvisionNginxIngress', 'Enabled']
  EnableExternalDNS: !Equals [!Ref 'ProvisionExternalDNS', 'Enabled']
  EnableDashboard: !Equals [!Ref 'ProvisionDashboard', 'Enabled']
  EnableNetwork: !Equals [!Ref 'ProvisionNetwork', 'Enabled']

Resources:
  
  #============================================================================#
  # Web Stack
  #============================================================================#
  ExternalDNSStack:
    Condition: EnableExternalDNS
    Type: AWS::CloudFormation::Stack
    Properties: 
      TemplateURL: https://s3.amazonaws.com/solodev-kubernetes/cloudformation/webstack/webstack-external-dns.template.yaml
      Parameters:
        ClusterName: !Ref ClusterName
  DashboardStack:
    DependsOn: ExternalDNSStack
    Condition: EnableDashboard
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://s3.amazonaws.com/solodev-kubernetes/cloudformation/webstack/webstack-dashboard.template.yaml
      Parameters:
        ClusterName: !Ref ClusterName
        CloudClientId: !Ref CloudClientId
        CloudClientSecret: !Ref CloudClientSecret
        CloudRedirectURI: !Ref CloudRedirectURI
        CloudAuthorizeURL: !Ref CloudAuthorizeURL
        CloudAccessToken: !Ref CloudAccessToken
        CloudKeySet: !Ref CloudKeySet
        OIDCUrl: !Ref OIDCUrl
  NginxIngressStack:
    DependsOn: ExternalDNSStack
    Condition: EnableNginxIngress
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://s3.amazonaws.com/solodev-kubernetes/cloudformation/webstack/webstack-nginx-ingress.template.yaml
      Parameters:
        ClusterName: !Ref ClusterName
  LetsEncryptStack:
    Condition: EnableNginxIngress
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://s3.amazonaws.com/solodev-kubernetes/cloudformation/webstack/webstack-lets-encrypt.template.yaml
      Parameters:
        ClusterName: !Ref ClusterName
        AdminEmail: !Ref AdminEmail
  NetworkStack:
    DependsOn: DashboardStack
    Condition: EnableNetwork
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://s3.amazonaws.com/solodev-kubernetes/cloudformation/webstack/webstack-network.template.yaml
      Parameters:
        ClusterName: !Ref ClusterName
        WebStackArn: !Ref WebStackArn

#============================================================================#
# Outputs
#============================================================================#

Outputs:
  AccessToken:
    Condition: EnableNetwork
    Value: !GetAtt NetworkStack.Outputs.AccessToken