AWSTemplateFormatVersion: "2010-09-09"

Description: "Deploys Salesforce"

Metadata: 

  AWS::CloudFormation::Interface: 
    ParameterGroups: 
      - 
        Label: 
          default: "Lambda Functions"
        Parameters: 
          - ClusterName
          - ClusterZone
          - WebStackArn
          - Namespace
      - 
        Label: 
          default: "Optional: SSO Configuration"
        Parameters: 
          - OIDCUrl
          - CloudClientId
          - CloudClientSecret
          - CloudRedirectURI
          - CloudAuthorizeURL
          - CloudAccessToken
          - CloudKeySet
          - CallbackURL

Parameters:

  WebStackArn:
    Type: String

  ClusterName:
    Type: String

  Namespace:
    Type: String
    Default: "solodev"

  ClusterZone:
    Description: This is the DNS Zone that for a single cluster
    Type: String
    Default: ""

  OIDCUrl:
    Type: String
    Description: "OIDC Url format: https://oidc.eks:<region>.amazonaws.com/id/<providerid>"

  CloudClientId:
    Type: String
    Description: AWS Cognito App Id

  CloudClientSecret:
    Type: String
    Description: AWS Cognito App Secret

  CloudRedirectURI:
    Type: String
    Default: ''

  CloudAuthorizeURL:
    Type: String
    Default: ''

  CloudAccessToken:
    Type: String
    Default: ''

  CloudKeySet:
    Type: String
    Default: ''

  CallbackURL:
    Type: String
    Default: ''

Resources:

  Salesforce:
    Type: "AWSQS::Kubernetes::Helm"
    Version: '1.0'
    Properties:
      ClusterID: !Ref ClusterName
      Namespace: !Ref Namespace
      Repository: "http://solodev-kubernetes.s3-website-us-east-1.amazonaws.com/charts"
      Chart: solodev/salesforce
      Name: !Ref AWS::StackName
      Version: 1.0
      ValueYaml: !Sub |
        provider:
          clientid: ${CloudClientId}
          clientsecret: ${CloudClientSecret}
          redirecturl: ${CloudRedirectURI}
          loginurl: ${CloudAuthorizeURL}
          redeemurl: ${CloudAccessToken}
          oidcjwksurl: ${CloudKeySet}
          oidcissuerurl: ${OIDCUrl}
          callbackurl: ${CallbackURL}
          domain: ${ClusterZone}

Outputs:
    
    AdminUrl: 
        Description: Point your DNS to this CNAME.
        Value: !Join ["", [ !Ref "AWS::StackName", ".", !Ref ClusterZone ]]
