AWSTemplateFormatVersion: "2010-09-09"

Description: "Enable Solodev Network, Storage Class, and get API token from an existing kubernetes cluster (qs-1qde66ffn)"

Metadata: 

  AWS::CloudFormation::Interface: 
    ParameterGroups: 
      - 
        Label: 
          default: "EKS Cluster"
        Parameters: 
          - WebStackArn
          - ClusterName

Parameters:

  WebStackArn:
    Type: String

  ClusterName:
    Type: String

Resources:

  Solodev:
    Type: "AWS::CloudFormation::CustomResource"
    Properties:
      ServiceToken: !Ref WebStackArn
      ClusterName: !Ref ClusterName
      Solodev:
        Enable: "true"

Outputs:
  AccessToken: 
    Value: !GetAtt Solodev.Token
    Description: Return secure access token